[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Opcional pero recomendado: especificar versión de Node
[build.environment]
  NODE_VERSION = "20"